#!/bin/sh -e
##:
#h: Usage: msetup-wireshark -w
##:
. wcompat
msetup_wireshark() {
    local OPTIND optopt opt_w=
    
    ## Parse command line arguments.
    while getopts "w" optopt; do
        case $optopt in
            w)  opt_w=y;;
            \?) return 1;;
        esac
    done
    shift $(( $OPTIND - 1 ))
    
    ##
    if test -n "${opt_w}"; then
        wcompat wrapper tshark <<-EOF
	#!/bin/sh -e
	chcp 65001 >/dev/null 2>&1
	'C:\\Program Files\\Wireshark\\tshark.exe' "\$@"
	EOF
        wcompat wrapper wireshark <<-EOF
	'C:\\Program Files\\Wireshark\\Wireshark.exe' "\$@"
	EOF
    fi
    
}
## -------------------------------------------------------------------
if test @"$(basename "$0")" = @"msetup-wireshark"; then
    case "${1}" in
        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0";;
        *)            msetup_wireshark "$@"; exit 0    ;;
    esac
fi
