#!/bin/sh -e
##:
#h: Usage: wsetup-google-chrome -w
##:
. wcompat
wsetup_google_chrome() {
    local OPTIND optopt opt_w=
    
    ## Parse command line arguments.
    while getopts "w" optopt; do
        case $optopt in
            w)  opt_w=y;;
            \?) return 1;;
        esac
    done
    shift $(( $OPTIND - 1 ))
    
    ## Create wrapper.
    if test -n "${opt_w}"; then
        wcompat wrapper google-chrome <<-EOF
	#!/bin/sh -e
	'C:/Program Files/Google/Chrome/Application/chrome.exe' "\$@"
	EOF
    fi
}
## -------------------------------------------------------------------
if test @"$(basename "$0")" = @"wsetup-google-chrome"; then
    case "${1}" in
        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0";;
        *)            wsetup_google_chrome "$@"; exit 0;;
    esac
fi
