#!/bin/sh -e
##:
#h: Usage: msetup-sumatra -i
##:
. wcompat
msetup_sumatra() {
    local u d x
    case "$(uname -m)" in
        x86_64) u="https://www.sumatrapdfreader.org/dl/rel/3.4.6/SumatraPDF-3.4.6-64-install.exe";;
        *)      u="https://www.sumatrapdfreader.org/dl/rel/3.4.6/SumatraPDF-3.4.6-install.exe";;
    esac
    d="C:/Program Files/SumatraPDF"
    x1="C:/Program Files/SumatraPDF/SumatraPDF.exe"
    wcompat chkadmin
    if test ! -e "${x1}" && test ! -e "${LOCALAPPDATA}/SumatraPDF/SumatraPDF.exe"; then
        wcompat fetch-INS "$u"
        wcompat g-exec "cmd /C $INS"
    fi
}
## -------------------------------------------------------------------
if test @"$(basename "$0")" = @"msetup-sumatra";then
    case "${1}" in
        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0";;
        -*i*)         msetup_sumatra "$@"; exit 0;;
    esac
fi
