#!/bin/sh -e
##:
#h: Usage: wsetup-nircmd -i
#h:
#h: Install nircmdc (https://www.nirsoft.net/utils/nircmd.html) command
#h: line utility.
##:
. wcompat
wsetup_nircmd() {
    case "$(uname -m)" in
        x86_64) local u="http://www.nirsoft.net/utils/nircmd-x64.zip";;
        *)      local u="http://www.nirsoft.net/utils/nircmd.zip";;
    esac
    wcompat chkadmin
    if test ! -e "$WBINDIR/nircmdc.exe"; then
        wcompat fetch-INS "$u"
        unzip "$INS" -d "$WBINDIR"
    fi
}
if test @"$(basename "$0")" = @"wsetup-nircmd";then
    case "${1}" in
        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0" ;;
        -*i*)         wsetup_nircmd "$@"; exit 0        ;;
    esac
fi
