#!/bin/sh -e
##:
#h: Usage: wsetup-sshfs -i
##:
wsetup_sshfs() {
    local u i

    INTERACTIVE=y
    
    u1="https://github.com/winfsp/winfsp/releases/download/v2.0/winfsp-2.0.23075.msi"
    i1="$(echo "${DDIR:-${TEMP:-/tmp}}/$(basename "${u1}")" | tr '/' '\\')"
    d1="C:/Program Files (x86)/WinFsp"

    case "$(uname -m)" in
        x86_64) u2="https://github.com/winfsp/sshfs-win/releases/download/v3.7.21011/sshfs-win-3.7.21011-x64.msi";;
        *)      u2="https://github.com/winfsp/sshfs-win/releases/download/v3.7.21011/sshfs-win-3.7.21011-x86.msi";;
    esac
    i2="$(echo "${DDIR:-${TEMP:-/tmp}}/$(basename "${u2}")" | tr '/' '\\')"
    d2="C:/Program Files/SSHFS-Win"
    
    ## WINFSP
    echo "Installing WinFSP ..."
    if test ! -e "${d1}/bin/winfsp-x64.sys"; then
        if test ! -e "${i1}"; then
            wget -O "${i1}.tmp" "${u1}"
            mv -v "${i1}.tmp" "${i1}"
        fi
        if test -n "${INTERACTIVE}"; then
            msiexec /i "${i1}"
        elif test @"$(whoami)" = @"root"; then
            msiexec /i "${i1}" /qn /norestart
        else
            echo "Execute this as administrator."
            return 1
        fi
        echo "WinFSP installed correctly, please restart the system."
        return 0
    fi
    
    ## SSHFS
    echo "Installing SSHFS ..."
    if test ! -e "${d2}/bin/sshfs-win.exe"; then
        if test ! -e "${i2}"; then
            wget -O "${i2}.tmp" "${u2}"
            mv -v "${i2}.tmp" "${i2}"
        fi
        if test -n "${INTERACTIVE}"; then
            msiexec /i "${i2}"
        elif test @"$(whoami)" = @"root"; then
            msiexec /i "${i2}" /qn /norestart
        else
            echo "Execute this as administrator."
            return 1
        fi
        echo "SSHFS installed correctly."
    fi

}
if test @"$(basename "$0")" = @"wsetup-sshfs";then
    case "${1}" in
        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0";;
        -*i*)         wsetup_sshfs "$@"; exit 0;;
    esac
fi
