#!/bin/sh -e
##:
#h: Usage: osetup-forwarding enable|disable|status
#h:
#h: Enable/disable forwarding with sysctl.
##:
. hmain
. hfile
. hlog
osetup_forwarding() {
    local cmd="$1"
    shift
    case "${cmd}" in
        enable)
            sysctl net.inet.ip.forwarding=1
            sysctl net.inet6.ip6.forwarding=1
            hfile cfadd /etc/sysctl.conf   \
                  net.inet.ip.forwarding=1 \
                  net.inet6.ip6.forwarding=1
            ;;
        disable)
            sysctl net.inet.ip.forwarding=0
            sysctl net.inet6.ip6.forwarding=0
            hfile cfadd /etc/sysctl.conf   \
                  net.inet.ip.forwarding=0 \
                  net.inet6.ip6.forwarding=0
            ;;
        status)
            sysctl net.inet.ip.forwarding
            ;;
        *)
            hlog error "Invalid argument: ${cmd}"
            return 1
            ;;
    esac
}
## -------------------------------------------------------------------
hmain -f "osetup-forwarding" osetup_forwarding "$@"
